#!/usr/bin/env sh
############################################################################
# Depends for run: zbarimg, qrencode, scrot
############################################################################


# Check depends
for check in 'zbarimg' 'qrencode' 'scrot'; do
    if ! type -P "$check" 1 >/dev/null 2>/dev/null; then
        echo "Please install $check"
        exit 1
    fi
done

if [ ! "$1" ]; then

    TMPDIR=/dev/shm
    cd "$TMPDIR"

    echo Use mouse select an area on screen to decode QR
    echo ""

    scrot -s -e 'echo Image size $w x $h ; echo "" ; zbarimg "$f" ; rm  "$f" '

else
    qrencode -m 2 -t ANSIUTF8 "$1"
fi
